# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be9729339fd00c8362f3d3651e12f55e9897165871c9b6fbc243adbaadb90fb91dcff8e63febcc9462336f3fa834540bbff10508f95b096602679f1d9c531244

test:
  secret_key_base: 74a256b128132820c95549d65df54d2cf3bae3a82f8c67157d9043b1151ffbbe96e3f7eb56eafd6321163133bd814430874652c951a1cf2b96cc899e237f3f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
